@endpoint = http://localhost:3000
@cognitoEndpoint = https://cognito-idp.ap-northeast-1.amazonaws.com/
@clientId = 35osoku2enj7t2bmrd41fjcbit
# account's username 
@username = e774caf8-0051-70e2-5f63-272f041b56a9
# account's password
@password = Abcd@1234
# account's email
@email = admin2@example.com

@apiBaseUrl = {{endpoint}}/api
@eventBaseUrl = {{endpoint}}/event

###
GET {{endpoint}} HTTP/1.1

###
# login
# @name login_cognito
POST {{cognitoEndpoint}}
Accept: application/json
Content-Type: application/x-amz-json-1.1
X-Amz-Target: AWSCognitoIdentityProviderService.InitiateAuth

{
  "AuthFlow": "USER_PASSWORD_AUTH",
  "ClientId": "{{clientId}}",
  "AuthParameters": {
    "USERNAME": "{{username}}",
    "PASSWORD": "{{password}}"
  },
  "ClientMetadata": {}
}

###
@token = {{login_cognito.response.body.AuthenticationResult.IdToken}}
###

# Health
GET {{endpoint}}
Accept: application/json
Authorization: {{token}}

###
# sample
POST {{apiBaseUrl}}/sample
Accept: application/json
Content-Type: application/json
Authorization: {{token}}
X-Tenant-Code: mbc

{
  "pk": "SAMPLE#mbc",
  "sk": "foo#bar",
  "id": "SAMPLE#mbc#foo#bar",
  "code": "foo#bar",
  "name": "Test",
  "version": 0,
  "isDeleted": true,
  "type": "SAMPLE",
  "tenantCode": "mbc",
  "attributes": {
    "value": {
      "foo": "bar"
    }
  }
}